export const INIT_APP = "INIT_APP";

export const COLUMN_COUNT = "COLUMN_COUNT";
export const ROW_COUNT = "ROW_COUNT";
export const PIXEL_SIZE = "PIXEL_SIZE";

export const BACKGROUND_COLOR = "BACKGROUND_COLOR";
export const BACKGROUND_RGB_COLOR = "BACKGROUND_RGB_COLOR";
export const PIXEL_COLOR = "PIXEL_COLOR";
export const CONVERTED_PIXEL_RGB_COLOR = "CONVERTED_PIXEL_RGB_COLOR";
export const PIXEL_RGB_COLOR = "PIXEL_RGB_COLOR";
