export const INIT_APP = "INIT_APP";

export const COLUMN_COUNT = "COLUMN_COUNT";
export const ROW_COUNT = "ROW_COUNT";
export const PIXEL_SIZE = "PIXEL_SIZE";

export const BACKGROUND_COLOR = "BACKGROUND_COLOR";
export const BACKGROUND_RGB_COLOR = "BACKGROUND_RGB_COLOR";
export const PIXEL_COLOR = "PIXEL_COLOR";
export const CONVERTED_PIXEL_RGB_COLOR = "CONVERTED_PIXEL_RGB_COLOR";
export const PIXEL_RGB_COLOR = "PIXEL_RGB_COLOR";

export const INIT_VIEW_MODE = "INIT_VIEW_MODE";
export const INIT_DRAW_MODE = "INIT_DRAW_MODE";
export const TOGGLE_GRID_VIEW = "TOGGLE_GRID_VIEW";
export const RESET_APP = "RESET_APP";

export const CANVAS_GRID_CLICKED = "CANVAS_GRID_CLICKED";
export const CANVAS_FILL_RECT_CLICKED = "CANVAS_FILL_RECT_CLICKED";

export const CODE_BOX_VIEW_CHANGED = "CODE_BOX-VIEW_CHANGED";
export const CODE_BOX_CSS_VIEW = "CODE_BOX_CSS_VIEW";
export const CODE_BOX_SASS_VIEW = "CODE_BOX_SASS_VIEW";
export const CODE_BOX_LESS_VIEW = "CODE_BOX_LESS_VIEW";
export const CODE_BOX_JS_VIEW = "CODE_BOX_JS_VIEW";
